Creates a new RPC endpoint for spending a TXO without a monitor
mobilecoinofficial/mobilecoin pull request #427
Opened 2020-09-09 02:10 UTC by tsegaran

Soundtrack of this PR: [I'm Free](https://www.youtube.com/watch?v=S6InAX5IAQM)

This is currently a draft, added TODO items

### Motivation

Currently there is no way to generate a transaction in mobilecoind without first setting up a monitor which then must view-key scan the entire ledger. In certain instances, for example gift codes, a caller may already know which UTXO they wish to spend, making scanning unnecessary. This PR adds a new RPC endpoint allowing a client to spend UTXOs with an account key without creating a monitor.

### In this PR
* Adds and implements `GenerateTxFromTxOutList` to the gRPC endpoint
* Adds a new function `generate_tx_from_tx_list` to `payments.rs`
* TODO: tests for the above
* TODO: update python library support these endpoints

2020-09-09 07:45 UTC, rjwalters commented
I would prefer we leave the API alone and accomplish this is steps:

1. AddMonitor 
1. GenerateTx 
1. SubmitTx 
1. RemoveMonitor

2020-09-09 18:10 UTC, eranrund commented
> I would prefer we leave the API alone and accomplish this in steps:
> 
>     1. GetLedgerInfo (to get `block_count`)
> 
>     2. AddMonitor (with `first_block = block_count`)
> 
>     3. GenerateTx
> 
>     4. SubmitTx
> 
>     5. GetTxStatusAsSender (confirm or retry on failure etc.)
> 
>     6. RemoveMonitor

I'd say that GetLedgerInfo is not even required, set first_block to max_u64-1. And yes, I agree that if multiple API calls are doable then this is going to be preferable than the custom API - but unclear if the user is willing to do that...
The new API call proposed here is actually similar to AddMonitor/GenerateTx/RemoveMonitor.  I think SubmitTx and GetTxStatusAsSender have to happen regardless...

2020-09-09 21:23 UTC, tsegaran commented
After discussion with @rjwalters and @eranrund I believe that this approach is the best path forward -- the one extra API call is not hard to maintain, it doesn't break any security properties and is consistent with the semantics of what the caller is actually doing.

2020-09-10 08:41 UTC, rjwalters commented on mobilecoind/src/payments.rs
> +        let fee = MINIMUM_FEE;
I think it would be better to anticipate setting fees in the future and pass this in with the Request

2020-09-11 19:41 UTC, eranrund requested changes
Some small stuff but other than that LGTM!

2020-09-11 19:41 UTC, eranrund commented on mobilecoind/clients/python/mob_client/mob_client.py
> +        return response.entropy, response.tx_public_key, response.memo, response.utxo
I think it would be better to just return `response`. This tuple means every change to it is a breaking change.

2020-09-11 19:41 UTC, eranrund commented on mobilecoind/src/payments.rs
> +            "Total transaction value excluding fees: {}",
This does not exclude the fee.

2020-09-11 19:41 UTC, eranrund commented on mobilecoind/src/payments.rs
> +            "Total transaction value excluding fees: {}",
There should be a check that total_value > fee.
If `fee` is 0, a default value should be used.

2020-09-11 20:36 UTC, eranrund approved these changes

2020-09-11 20:49 UTC, sugargoat approved these changes

2020-09-11 20:50 UTC, merged