Adds moburl to returned proto when creating a request code
mobilecoinofficial/mobilecoin pull request #476
Opened 2020-09-25 22:14 UTC by tsegaran

### Motivation

Product spec includes QR codes for request codes in desktop clients, these should be encoded as mob_urls 

### In this PR
* Return mob_url  as part of CreateRequestCode in mobilecoind

### Future Work
* If we like this approach, also add to transfer codes?

2020-09-25 22:18 UTC, jcape approved these changes

2020-09-26 09:35 UTC, rjwalters approved these changes
Please create a Jira ticket to extend the moburl scheme to cover transfer codes. We will need this for the desktop client to export gift codes.

2020-09-28 16:39 UTC, voloshyn requested changes
Please add mob_url property to Transfer and PublicAddress payloads. Those are needed for the mobile wallet.

2020-09-28 21:28 UTC, tsegaran commented
I have added the mob_url to the public address call, and created a ticket to do it for transfer codes

2020-09-28 21:39 UTC, merged